#+title: laooree's Arch Linux dotfiles
#+author: laooree
#+description: My Arch Linux dotfiles, nicely presented in org-mode
#+startup: content
#+auto_tangle: t

This =org= file describes my dotfiles. If you use =Emacs=, you can just download
this file and put it in a =~/dotfiles= folder, then use =org-babel-tangle=
command: it will automatically generate all the dotfiles with the correct folder
structure. From there, just link them to their appropriate location (I suggest
using GNU =stow=). The files in =import= folder *are NOT* specified in this
=org= file.

*DISCLAIMER:* These are my personal dotfiles, and come without warranties (see
=LICENSE=). Make sure you know what they do before using them. Furthermore, they
need to fit my use-case before anyone else's: that said, feel free to contribute
if you see any margin for improvements.

* Zshell

My =zsh= configuration:
- =~/.zprofile= containing environment variables;
- =~/.zshrc= containing my =zsh= configuraition. This is also sourcing the
  global aliases file.

** .zprofile

This file sets some env vars. It tries to follow the [[https://specifications.freedesktop.org/basedir-spec/latest/][XDG base directory
specifications]].

#+begin_src sh :tangle "zsh/.zprofile"
  #!/bin/sh
  # env vars to set on login, zsh settings in ~/config/zsh/.zshrc

  # default programs
  export EDITOR="vi"
  export TERM="kitty"
  export TERMINAL="kitty"
  export BROWSER="firefox"
  # export BROWSER2="librewolf"

  # XDG config
  export XDG_CONFIG_HOME="$HOME/.config"
  export XDG_CACHE_HOME="$HOME/.cache"
  export XDG_DATA_HOME="$HOME/.local/share"
  export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
  export XPROFILE="$XDG_CONFIG_HOME/x11/xprofile"
  export XRESOURCES="$XDG_CONFIG_HOME/x11/xresources"

  # zsh
  export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
  export ZSH_COMPDUMP="$XDG_CACHE_HOME/.zcompdump"

  # history
  export LESSHISTFILE="$XDG_CACHE_HOME/less_history"

  # xdg data
  export CARGO_HOME="$XDG_DATA_HOME/cargo"
  export GOPATH="$XDG_DATA_HOME/go"
  export GOBIN="$GOPATH/bin"
  export GOMODCACHE="$XDG_CACHE_HOME/go/mod"

#+end_src

** .zshrc

First of all, source =.zprofile= if needed. It is sourced by default only in
login shells. However, when starting the system using a display manager the
shell is not startet as a login shell.

#+begin_src sh :tangle "zsh/.zshrc"
  # If not a login shell, manually source .zprofile
  if [[ ! -o login && -f ~/.zprofile ]]; then
    source ~/.zprofile
  fi

#+end_src

Then, source the alias file:

#+begin_src sh :tangle "zsh/.zshrc"

  # Source shell aliases
  [ -f "$XDG_CONFIG_HOME/shell/alias" ] && source "$XDG_CONFIG_HOME/shell/alias"

#+end_src

Load the completion and shell colors modules.

#+begin_src sh :tangle "zsh/.zshrc"

  # load modules
  zmodload zsh/complist
  autoload -U compinit && compinit -C
  autoload -U colors && colors

#+end_src

This part is configuring stuff.

#+begin_src sh :tangle "zsh/.zshrc"

  # configure completions
  zstyle ':completion:*' menu select # tab opens cmp menu
  zstyle ':completion:*' special-dirs true # force . and .. to show in cmp menu
  zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS} ma=0\;33 # colorize cmp menu
  # zstyle ':completion:*' file-list true # more detailed list
  zstyle ':completion:*' squeeze-slashes false # explicit disable to allow /*/
  # expansion

  # main opts
  setopt append_history inc_append_history share_history # better history on exit,
  # history appends rather than overwrites; history is appended as soon as cmds
  # executed; history shared across sessions
  setopt auto_menu menu_complete # autocmp first menu match
  # setopt autocd # type a dir to cd
  setopt auto_param_slash # if dir is completed, add / instead of space
  setopt no_case_glob no_case_match # make cmp case insensitive
  setopt globdots # match .files too
  setopt extended_glob # match ~ # ^
  # setopt interactive_comments # allow comments in shell
  # unsetopt prompt_sp # don't autoclean blanklines
  stty stop undef # disable accidental ctrl s

  # history opts
  HISTSIZE=1000000
  SAVEHIST=1000000
  HISTFILE="$XDG_CACHE_HOME/zsh_history" # move histfile to cache
  HISTCONTROL=ignoreboth # consecutive duplicates & commands starting with space
                         # are not saved

#+end_Src

Finally, a custom shell prompt is set here.

#+begin_src sh :tangle "zsh/.zshrc"

  # Prompt
  NEWLINE=$'\n'
  PROMPT="${NEWLINE}%F{#1793D1}   %F{#A7C080} %n in %~${NEWLINE}  ❯ %f%k"

#+end_src

* Shell aliases

Shell aliases are specified in this file, located in
=~/.config/shell/alias=.

#+begin_src sh :tangle "shell-aliases/.config/shell/alias"
  alias c="clear"
  alias v="nvim"
  alias cat="bat"
  alias ls="ls -h --color=auto --group-directories-first"
  alias la="ls -ah --color=auto --group-directories-first"
  alias ll="ls -lah --color=auto --group-directories-first"
  alias grep="grep --color=auto"
  alias mv="mv -i"
  alias rm="rm -Iv"
  alias p="ps aux | grep $1"

#+end_src

